language: rust
dist: bionic
addons:
  apt:
    packages:
    - rpm
env:
  - PACKAGECLOUD_TOKEN=702e59bc0a8d050b6da2a70425ed476fc9d802ce5ff9dac1
rust:
  - stable
jobs:
  fast_finish: true
cache: cargo
before_install:
  - gem install package_cloud
install:
  - cargo install cargo-rpm
script:
  - cargo test --verbose --all
#after_success:
  - cargo rpm build -v
#  - ls target/release/rpmbuild/RPMS
#  - ls target/release/rpmbuild/RPMS/x86_64/
#  - package_cloud push timgabets/lakgves/fedora/28 lakgves/target/release/rpmbuild/RPMS/x86_64/*.rpm

deploy:
  provider: releases
  api_key: 0c5b1378bf3e9b064b8ccf5735957497c46ecbca
  file: target/release/rpmbuild/RPMS/x86_64/lakgves-0.1.16-1.x86_64.rpm
  skip_cleanup: true
