language: rust
dist: bionic
addons:
  apt:
    packages:
    - rpmbuild
rust:
  - stable
jobs:
  fast_finish: true
#cache: cargo
install:
  - cargo install cargo-rpm
script:
  - cargo test --verbose --all
after_success:
  - apt-get install rpmbuild