[package]
name = "proust"
version = "0.1.1"
authors = ["Tim Gabets <tim@gabets.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.106"
serde_json = "1.0"
serde-xml-rs = "0.4.0"
serde_derive = "1.0.106"
