
[listener]
# Host and TCP port to listen to incoming requests
listen = "localhost:8080"

# Number of workers to process incoming requests.
# If not specified or 0, the number of logical CPUs will be used
n_workers= 4

[channels]
	# NOTE: The channel name will be used as API entrypoint. E.g. for the channel below
	# the entrypoint is http://localhost:8080/dhi
	[channels.dhi]
	# Currently DHI (Debit Host Interface) XML is the only supported type
	#format = "DHI-XML"
	# Host to connect to
	host = "host.bank.com"
	# TCP port to connect to
	port = 10309
	# Connection keep alive (seconds)
	keep_alive = 75
