
[listener]
# TCP port to listen to incoming requests
port = 8080

[channels]
	[channels.acq]
	# Currently XML is the only supported type
	type = "XML"
	# Host to connect to
	host = "host.bank.com"
	# TCP port to connect to
	port = 10309
	# whether the connection is synchronous or asynchronous
	async = true
	# Number of seconds to wait for response from the host
	timeout = 30
